package commands

import (
	"fmt"
	"path/filepath"
	"strconv"
	"time"

	"github.com/hasura/graphql-engine/cli"
	"github.com/spf13/cobra"
)

type seedNewOptions struct {
	ec *cli.ExecutionContext

	// filename for the new seed file, note: this is autogenerated
	filename string
}

func newSeedCreateCmd(ec *cli.ExecutionContext) *cobra.Command {
	opts := seedNewOptions{
		ec: ec,
	}
	cmd := &cobra.Command{
		Use:          "new",
		Short:        "create a new seed file",
		SilenceUsage: false,
		RunE: func(cmd *cobra.Command, args []string) error {
			opts.filename = args[0]
			return opts.run()
		},
		Args: cobra.ExactArgs(1),
	}

	return cmd
}

func (o *seedNewOptions) run() error {
	timestamp := strconv.FormatInt(time.Now().UnixNano()/int64(time.Millisecond), 10)
	fileNameWithTimeStamp := fmt.Sprintf("%d", timestamp)
	fullFilePath := filepath.Join(o.ec.SeedsDirectory, fileNameWithTimeStamp)

	fmt.Println(fullFilePath)
	return nil
}
